### ISSUE TITLE
mobile close link

### ISSUE THREAD

**Issue by ed-g** [livemixlove/salemheader#1]
On mobile, the way the Close link falls down looks a bit strange. Is there a way to make this look better?

Note the version of the code we are using on Salem is https://github.com/ed-g/otp.js/tree/master/client_salem_with_header

**Comment by ed-g** [comment]
Comment from Matt at https://basecamp.com/2316867/projects/3251794/todos/93542845#comment_326422813

**Comment by livemixlove** [comment]
Done
